[project]
name = "lpr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "graphviz>=0.20.3",
    "jaxtyping>=0.3.2",
    "k2>=1.24.0",
    "opencv-python>=4.11.0.86",
    "torch>=2.7.0",
    "ultralytics>=8.3.146",
]
