[project]
name = "lpr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "graphviz>=0.20.3",
    "jaxtyping>=0.3.2",
    "k2>=0.3.0",
    "torch>=2.7.0",
    "ultralytics>=8.3.146",
]
